import 'package:v2log/shared/models/exercise_model.dart';
import 'package:v2log/shared/models/routine_model.dart';
import 'dummy_exercises.dart';

/// 더미 사용자 루틴 데이터
class DummyRoutines {
  DummyRoutines._();

  static final List<RoutineModel> routines = [
    RoutineModel(
      id: 'routine-001',
      userId: 'demo-user',
      name: '내 가슴 루틴',
      description: '가슴 중심 루틴',
      sourceType: RoutineSourceType.custom,
      targetMuscles: [MuscleGroup.chest, MuscleGroup.triceps],
      estimatedDuration: 45,
      isActive: true,
      exercises: [
        RoutineExerciseModel(
          id: 're-001',
          routineId: 'routine-001',
          exerciseId: 'ex-001',
          orderIndex: 0,
          targetSets: 4,
          targetReps: '8-10',
          restSeconds: 120,
          exercise: DummyExercises.getById('ex-001'),
        ),
        RoutineExerciseModel(
          id: 're-002',
          routineId: 'routine-001',
          exerciseId: 'ex-002',
          orderIndex: 1,
          targetSets: 3,
          targetReps: '10-12',
          restSeconds: 90,
          exercise: DummyExercises.getById('ex-002'),
        ),
        RoutineExerciseModel(
          id: 're-003',
          routineId: 'routine-001',
          exerciseId: 'ex-003',
          orderIndex: 2,
          targetSets: 3,
          targetReps: '12-15',
          restSeconds: 60,
          exercise: DummyExercises.getById('ex-003'),
        ),
        RoutineExerciseModel(
          id: 're-004',
          routineId: 'routine-001',
          exerciseId: 'ex-032',
          orderIndex: 3,
          targetSets: 3,
          targetReps: '12-15',
          restSeconds: 60,
          exercise: DummyExercises.getById('ex-032'),
        ),
      ],
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    RoutineModel(
      id: 'routine-002',
      userId: 'demo-user',
      name: '내 등 루틴',
      description: '등과 이두 루틴',
      sourceType: RoutineSourceType.custom,
      targetMuscles: [MuscleGroup.back, MuscleGroup.lats, MuscleGroup.biceps],
      estimatedDuration: 50,
      isActive: true,
      exercises: [
        RoutineExerciseModel(
          id: 're-010',
          routineId: 'routine-002',
          exerciseId: 'ex-010',
          orderIndex: 0,
          targetSets: 4,
          targetReps: '5-6',
          restSeconds: 180,
          exercise: DummyExercises.getById('ex-010'),
        ),
        RoutineExerciseModel(
          id: 're-011',
          routineId: 'routine-002',
          exerciseId: 'ex-011',
          orderIndex: 1,
          targetSets: 4,
          targetReps: '10-12',
          restSeconds: 90,
          exercise: DummyExercises.getById('ex-011'),
        ),
        RoutineExerciseModel(
          id: 're-012',
          routineId: 'routine-002',
          exerciseId: 'ex-012',
          orderIndex: 2,
          targetSets: 3,
          targetReps: '10-12',
          restSeconds: 90,
          exercise: DummyExercises.getById('ex-012'),
        ),
        RoutineExerciseModel(
          id: 're-013',
          routineId: 'routine-002',
          exerciseId: 'ex-030',
          orderIndex: 3,
          targetSets: 3,
          targetReps: '10-12',
          restSeconds: 60,
          exercise: DummyExercises.getById('ex-030'),
        ),
      ],
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    RoutineModel(
      id: 'routine-003',
      userId: 'demo-user',
      name: '내 하체 루틴',
      description: '하체 전체 루틴',
      sourceType: RoutineSourceType.custom,
      targetMuscles: [MuscleGroup.quads, MuscleGroup.hamstrings, MuscleGroup.glutes],
      estimatedDuration: 55,
      isActive: true,
      exercises: [
        RoutineExerciseModel(
          id: 're-020',
          routineId: 'routine-003',
          exerciseId: 'ex-040',
          orderIndex: 0,
          targetSets: 4,
          targetReps: '6-8',
          restSeconds: 180,
          exercise: DummyExercises.getById('ex-040'),
        ),
        RoutineExerciseModel(
          id: 're-021',
          routineId: 'routine-003',
          exerciseId: 'ex-041',
          orderIndex: 1,
          targetSets: 3,
          targetReps: '10-12',
          restSeconds: 120,
          exercise: DummyExercises.getById('ex-041'),
        ),
        RoutineExerciseModel(
          id: 're-022',
          routineId: 'routine-003',
          exerciseId: 'ex-043',
          orderIndex: 2,
          targetSets: 3,
          targetReps: '10-12',
          restSeconds: 90,
          exercise: DummyExercises.getById('ex-043'),
        ),
        RoutineExerciseModel(
          id: 're-023',
          routineId: 'routine-003',
          exerciseId: 'ex-044',
          orderIndex: 3,
          targetSets: 3,
          targetReps: '10-12',
          restSeconds: 90,
          exercise: DummyExercises.getById('ex-044'),
        ),
        RoutineExerciseModel(
          id: 're-024',
          routineId: 'routine-003',
          exerciseId: 'ex-046',
          orderIndex: 4,
          targetSets: 4,
          targetReps: '15-20',
          restSeconds: 60,
          exercise: DummyExercises.getById('ex-046'),
        ),
      ],
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    RoutineModel(
      id: 'routine-004',
      userId: 'demo-user',
      name: '어깨 데이',
      description: '어깨 집중 루틴',
      sourceType: RoutineSourceType.template,
      targetMuscles: [MuscleGroup.shoulders],
      estimatedDuration: 40,
      isActive: true,
      exercises: [
        RoutineExerciseModel(
          id: 're-030',
          routineId: 'routine-004',
          exerciseId: 'ex-020',
          orderIndex: 0,
          targetSets: 4,
          targetReps: '6-8',
          restSeconds: 120,
          exercise: DummyExercises.getById('ex-020'),
        ),
        RoutineExerciseModel(
          id: 're-031',
          routineId: 'routine-004',
          exerciseId: 'ex-021',
          orderIndex: 1,
          targetSets: 3,
          targetReps: '10-12',
          restSeconds: 90,
          exercise: DummyExercises.getById('ex-021'),
        ),
        RoutineExerciseModel(
          id: 're-032',
          routineId: 'routine-004',
          exerciseId: 'ex-022',
          orderIndex: 2,
          targetSets: 3,
          targetReps: '12-15',
          restSeconds: 60,
          exercise: DummyExercises.getById('ex-022'),
        ),
        RoutineExerciseModel(
          id: 're-033',
          routineId: 'routine-004',
          exerciseId: 'ex-023',
          orderIndex: 3,
          targetSets: 3,
          targetReps: '12-15',
          restSeconds: 60,
          exercise: DummyExercises.getById('ex-023'),
        ),
        RoutineExerciseModel(
          id: 're-034',
          routineId: 'routine-004',
          exerciseId: 'ex-024',
          orderIndex: 4,
          targetSets: 3,
          targetReps: '15-20',
          restSeconds: 60,
          exercise: DummyExercises.getById('ex-024'),
        ),
      ],
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    RoutineModel(
      id: 'routine-005',
      userId: 'demo-user',
      name: '코어 강화',
      description: '복근 및 코어 루틴',
      sourceType: RoutineSourceType.custom,
      targetMuscles: [MuscleGroup.abs, MuscleGroup.obliques],
      estimatedDuration: 25,
      isActive: true,
      exercises: [
        RoutineExerciseModel(
          id: 're-040',
          routineId: 'routine-005',
          exerciseId: 'ex-052',
          orderIndex: 0,
          targetSets: 3,
          targetReps: '60초',
          restSeconds: 60,
          exercise: DummyExercises.getById('ex-052'),
        ),
        RoutineExerciseModel(
          id: 're-041',
          routineId: 'routine-005',
          exerciseId: 'ex-050',
          orderIndex: 1,
          targetSets: 3,
          targetReps: '15-20',
          restSeconds: 45,
          exercise: DummyExercises.getById('ex-050'),
        ),
        RoutineExerciseModel(
          id: 're-042',
          routineId: 'routine-005',
          exerciseId: 'ex-051',
          orderIndex: 2,
          targetSets: 3,
          targetReps: '12-15',
          restSeconds: 45,
          exercise: DummyExercises.getById('ex-051'),
        ),
        RoutineExerciseModel(
          id: 're-043',
          routineId: 'routine-005',
          exerciseId: 'ex-053',
          orderIndex: 3,
          targetSets: 3,
          targetReps: '20회 (좌우)',
          restSeconds: 45,
          exercise: DummyExercises.getById('ex-053'),
        ),
      ],
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now().subtract(const Duration(days: 7)),
    ),
  ];

  /// ID로 루틴 가져오기
  static RoutineModel? getById(String id) {
    try {
      return routines.firstWhere((r) => r.id == id);
    } catch (_) {
      return null;
    }
  }

  /// 활성 루틴 가져오기
  static List<RoutineModel> getActive() {
    return routines.where((r) => r.isActive).toList();
  }

  /// 근육 부위별 루틴 가져오기
  static List<RoutineModel> getByMuscle(MuscleGroup muscle) {
    return routines.where((r) => r.targetMuscles.contains(muscle)).toList();
  }
}
